### ISSUE TITLE
Clarify in account naming: Expense vs Expenses

### ISSUE THREAD

**Issue by robbat2** [conservancy/npo-ledger-cli#1]
The tutorial uses examples with both Expense: (singular) and Expenses: (plural); is this a typo or do both hierarchies exist?

**Comment by tbm** [comment]
I'm not the author but I'd say this is a typo. It should imho be plural.

**Comment by tbm** [comment]
I can confirm that Conservancy only uses Expenses: (plural).

**Comment by bkuhn** [comment]
438e0688929da670bdc37c99baf213f55ef0f8b0 normalizes this to Expenses.

Meanwhile, I'm turning off the Issue tracker here.  Please use https://k.sfconservancy.org/npo-ledger-cli for collaboration.
